spring:
  application:
    name: Sinance-API
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

api:
  security:
    token:
      secret: ${TOKEN_SECRET}
